/*
 * Copyright (c) 2022 Hiroshi ARAKI. All Rights Reserved.
 */

package net.hirlab.ktsignage.config

/**
 * Countries supported by this application.
 * @property itemName country name in English
 * @property value alpha-2 country code
 */
enum class Country(override val itemName: String, override val value: String) : SettingItem {
    AW(itemName = "Aruba", value = "AW"),
    AF(itemName = "Afghanistan", value = "AF"),
    AO(itemName = "Angola", value = "AO"),
    AI(itemName = "Anguilla", value = "AI"),
    AX(itemName = "Åland Islands", value = "AX"),
    AL(itemName = "Albania", value = "AL"),
    AD(itemName = "Andorra", value = "AD"),
    AE(itemName = "United Arab Emirates", value = "AE"),
    AR(itemName = "Argentina", value = "AR"),
    AM(itemName = "Armenia", value = "AM"),
    AS(itemName = "American Samoa", value = "AS"),
    AQ(itemName = "Antarctica", value = "AQ"),
    TF(itemName = "French Southern Territories", value = "TF"),
    AG(itemName = "Antigua and Barbuda", value = "AG"),
    AU(itemName = "Australia", value = "AU"),
    AT(itemName = "Austria", value = "AT"),
    AZ(itemName = "Azerbaijan", value = "AZ"),
    BI(itemName = "Burundi", value = "BI"),
    BE(itemName = "Belgium", value = "BE"),
    BJ(itemName = "Benin", value = "BJ"),
    BQ(itemName = "Bonaire, Sint Eustatius and Saba", value = "BQ"),
    BF(itemName = "Burkina Faso", value = "BF"),
    BD(itemName = "Bangladesh", value = "BD"),
    BG(itemName = "Bulgaria", value = "BG"),
    BH(itemName = "Bahrain", value = "BH"),
    BS(itemName = "Bahamas", value = "BS"),
    BA(itemName = "Bosnia and Herzegovina", value = "BA"),
    BL(itemName = "Saint Barthélemy", value = "BL"),
    BY(itemName = "Belarus", value = "BY"),
    BZ(itemName = "Belize", value = "BZ"),
    BM(itemName = "Bermuda", value = "BM"),
    BO(itemName = "Bolivia, Plurinational State of", value = "BO"),
    BR(itemName = "Brazil", value = "BR"),
    BB(itemName = "Barbados", value = "BB"),
    BN(itemName = "Brunei Darussalam", value = "BN"),
    BT(itemName = "Bhutan", value = "BT"),
    BV(itemName = "Bouvet Island", value = "BV"),
    BW(itemName = "Botswana", value = "BW"),
    CF(itemName = "Central African Republic", value = "CF"),
    CA(itemName = "Canada", value = "CA"),
    CC(itemName = "Cocos (Keeling) Islands", value = "CC"),
    CH(itemName = "Switzerland", value = "CH"),
    CL(itemName = "Chile", value = "CL"),
    CN(itemName = "China", value = "CN"),
    CI(itemName = "Côte d'Ivoire", value = "CI"),
    CM(itemName = "Cameroon", value = "CM"),
    CD(itemName = "Congo, The Democratic Republic of the", value = "CD"),
    CG(itemName = "Congo", value = "CG"),
    CK(itemName = "Cook Islands", value = "CK"),
    CO(itemName = "Colombia", value = "CO"),
    KM(itemName = "Comoros", value = "KM"),
    CV(itemName = "Cabo Verde", value = "CV"),
    CR(itemName = "Costa Rica", value = "CR"),
    CU(itemName = "Cuba", value = "CU"),
    CW(itemName = "Curaçao", value = "CW"),
    CX(itemName = "Christmas Island", value = "CX"),
    KY(itemName = "Cayman Islands", value = "KY"),
    CY(itemName = "Cyprus", value = "CY"),
    CZ(itemName = "Czechia", value = "CZ"),
    DE(itemName = "Germany", value = "DE"),
    DJ(itemName = "Djibouti", value = "DJ"),
    DM(itemName = "Dominica", value = "DM"),
    DK(itemName = "Denmark", value = "DK"),
    DO(itemName = "Dominican Republic", value = "DO"),
    DZ(itemName = "Algeria", value = "DZ"),
    EC(itemName = "Ecuador", value = "EC"),
    EG(itemName = "Egypt", value = "EG"),
    ER(itemName = "Eritrea", value = "ER"),
    EH(itemName = "Western Sahara", value = "EH"),
    ES(itemName = "Spain", value = "ES"),
    EE(itemName = "Estonia", value = "EE"),
    ET(itemName = "Ethiopia", value = "ET"),
    FI(itemName = "Finland", value = "FI"),
    FJ(itemName = "Fiji", value = "FJ"),
    FK(itemName = "Falkland Islands (Malvinas)", value = "FK"),
    FR(itemName = "France", value = "FR"),
    FO(itemName = "Faroe Islands", value = "FO"),
    FM(itemName = "Micronesia, Federated States of", value = "FM"),
    GA(itemName = "Gabon", value = "GA"),
    GB(itemName = "United Kingdom", value = "GB"),
    GE(itemName = "Georgia", value = "GE"),
    GG(itemName = "Guernsey", value = "GG"),
    GH(itemName = "Ghana", value = "GH"),
    GI(itemName = "Gibraltar", value = "GI"),
    GN(itemName = "Guinea", value = "GN"),
    GP(itemName = "Guadeloupe", value = "GP"),
    GM(itemName = "Gambia", value = "GM"),
    GW(itemName = "Guinea-Bissau", value = "GW"),
    GQ(itemName = "Equatorial Guinea", value = "GQ"),
    GR(itemName = "Greece", value = "GR"),
    GD(itemName = "Grenada", value = "GD"),
    GL(itemName = "Greenland", value = "GL"),
    GT(itemName = "Guatemala", value = "GT"),
    GF(itemName = "French Guiana", value = "GF"),
    GU(itemName = "Guam", value = "GU"),
    GY(itemName = "Guyana", value = "GY"),
    HK(itemName = "Hong Kong", value = "HK"),
    HM(itemName = "Heard Island and McDonald Islands", value = "HM"),
    HN(itemName = "Honduras", value = "HN"),
    HR(itemName = "Croatia", value = "HR"),
    HT(itemName = "Haiti", value = "HT"),
    HU(itemName = "Hungary", value = "HU"),
    ID(itemName = "Indonesia", value = "ID"),
    IM(itemName = "Isle of Man", value = "IM"),
    IN(itemName = "India", value = "IN"),
    IO(itemName = "British Indian Ocean Territory", value = "IO"),
    IE(itemName = "Ireland", value = "IE"),
    IR(itemName = "Iran, Islamic Republic of", value = "IR"),
    IQ(itemName = "Iraq", value = "IQ"),
    IS(itemName = "Iceland", value = "IS"),
    IL(itemName = "Israel", value = "IL"),
    IT(itemName = "Italy", value = "IT"),
    JM(itemName = "Jamaica", value = "JM"),
    JE(itemName = "Jersey", value = "JE"),
    JO(itemName = "Jordan", value = "JO"),
    JP(itemName = "Japan", value = "JP"),
    KZ(itemName = "Kazakhstan", value = "KZ"),
    KE(itemName = "Kenya", value = "KE"),
    KG(itemName = "Kyrgyzstan", value = "KG"),
    KH(itemName = "Cambodia", value = "KH"),
    KI(itemName = "Kiribati", value = "KI"),
    KN(itemName = "Saint Kitts and Nevis", value = "KN"),
    KR(itemName = "Korea, Republic of", value = "KR"),
    KW(itemName = "Kuwait", value = "KW"),
    LA(itemName = "Lao People's Democratic Republic", value = "LA"),
    LB(itemName = "Lebanon", value = "LB"),
    LR(itemName = "Liberia", value = "LR"),
    LY(itemName = "Libya", value = "LY"),
    LC(itemName = "Saint Lucia", value = "LC"),
    LI(itemName = "Liechtenstein", value = "LI"),
    LK(itemName = "Sri Lanka", value = "LK"),
    LS(itemName = "Lesotho", value = "LS"),
    LT(itemName = "Lithuania", value = "LT"),
    LU(itemName = "Luxembourg", value = "LU"),
    LV(itemName = "Latvia", value = "LV"),
    MO(itemName = "Macao", value = "MO"),
    MF(itemName = "Saint Martin (French part)", value = "MF"),
    MA(itemName = "Morocco", value = "MA"),
    MC(itemName = "Monaco", value = "MC"),
    MD(itemName = "Moldova, Republic of", value = "MD"),
    MG(itemName = "Madagascar", value = "MG"),
    MV(itemName = "Maldives", value = "MV"),
    MX(itemName = "Mexico", value = "MX"),
    MH(itemName = "Marshall Islands", value = "MH"),
    MK(itemName = "North Macedonia", value = "MK"),
    ML(itemName = "Mali", value = "ML"),
    MT(itemName = "Malta", value = "MT"),
    MM(itemName = "Myanmar", value = "MM"),
    ME(itemName = "Montenegro", value = "ME"),
    MN(itemName = "Mongolia", value = "MN"),
    MP(itemName = "Northern Mariana Islands", value = "MP"),
    MZ(itemName = "Mozambique", value = "MZ"),
    MR(itemName = "Mauritania", value = "MR"),
    MS(itemName = "Montserrat", value = "MS"),
    MQ(itemName = "Martinique", value = "MQ"),
    MU(itemName = "Mauritius", value = "MU"),
    MW(itemName = "Malawi", value = "MW"),
    MY(itemName = "Malaysia", value = "MY"),
    YT(itemName = "Mayotte", value = "YT"),
    NA(itemName = "Namibia", value = "NA"),
    NC(itemName = "New Caledonia", value = "NC"),
    NE(itemName = "Niger", value = "NE"),
    NF(itemName = "Norfolk Island", value = "NF"),
    NG(itemName = "Nigeria", value = "NG"),
    NI(itemName = "Nicaragua", value = "NI"),
    NU(itemName = "Niue", value = "NU"),
    NL(itemName = "Netherlands", value = "NL"),
    NO(itemName = "Norway", value = "NO"),
    NP(itemName = "Nepal", value = "NP"),
    NR(itemName = "Nauru", value = "NR"),
    NZ(itemName = "New Zealand", value = "NZ"),
    OM(itemName = "Oman", value = "OM"),
    PK(itemName = "Pakistan", value = "PK"),
    PA(itemName = "Panama", value = "PA"),
    PN(itemName = "Pitcairn", value = "PN"),
    PE(itemName = "Peru", value = "PE"),
    PH(itemName = "Philippines", value = "PH"),
    PW(itemName = "Palau", value = "PW"),
    PG(itemName = "Papua New Guinea", value = "PG"),
    PL(itemName = "Poland", value = "PL"),
    PR(itemName = "Puerto Rico", value = "PR"),
    KP(itemName = "Korea, Democratic People's Republic of", value = "KP"),
    PT(itemName = "Portugal", value = "PT"),
    PY(itemName = "Paraguay", value = "PY"),
    PS(itemName = "Palestine, State of", value = "PS"),
    PF(itemName = "French Polynesia", value = "PF"),
    QA(itemName = "Qatar", value = "QA"),
    RE(itemName = "Réunion", value = "RE"),
    RO(itemName = "Romania", value = "RO"),
    RU(itemName = "Russian Federation", value = "RU"),
    RW(itemName = "Rwanda", value = "RW"),
    SA(itemName = "Saudi Arabia", value = "SA"),
    SD(itemName = "Sudan", value = "SD"),
    SN(itemName = "Senegal", value = "SN"),
    SG(itemName = "Singapore", value = "SG"),
    GS(itemName = "South Georgia and the South Sandwich Islands", value = "GS"),
    SH(itemName = "Saint Helena, Ascension and Tristan da Cunha", value = "SH"),
    SJ(itemName = "Svalbard and Jan Mayen", value = "SJ"),
    SB(itemName = "Solomon Islands", value = "SB"),
    SL(itemName = "Sierra Leone", value = "SL"),
    SV(itemName = "El Salvador", value = "SV"),
    SM(itemName = "San Marino", value = "SM"),
    SO(itemName = "Somalia", value = "SO"),
    PM(itemName = "Saint Pierre and Miquelon", value = "PM"),
    RS(itemName = "Serbia", value = "RS"),
    SS(itemName = "South Sudan", value = "SS"),
    ST(itemName = "Sao Tome and Principe", value = "ST"),
    SR(itemName = "Suriname", value = "SR"),
    SK(itemName = "Slovakia", value = "SK"),
    SI(itemName = "Slovenia", value = "SI"),
    SE(itemName = "Sweden", value = "SE"),
    SZ(itemName = "Eswatini", value = "SZ"),
    SX(itemName = "Sint Maarten (Dutch part)", value = "SX"),
    SC(itemName = "Seychelles", value = "SC"),
    SY(itemName = "Syrian Arab Republic", value = "SY"),
    TC(itemName = "Turks and Caicos Islands", value = "TC"),
    TD(itemName = "Chad", value = "TD"),
    TG(itemName = "Togo", value = "TG"),
    TH(itemName = "Thailand", value = "TH"),
    TJ(itemName = "Tajikistan", value = "TJ"),
    TK(itemName = "Tokelau", value = "TK"),
    TM(itemName = "Turkmenistan", value = "TM"),
    TL(itemName = "Timor-Leste", value = "TL"),
    TO(itemName = "Tonga", value = "TO"),
    TT(itemName = "Trinidad and Tobago", value = "TT"),
    TN(itemName = "Tunisia", value = "TN"),
    TR(itemName = "Turkey", value = "TR"),
    TV(itemName = "Tuvalu", value = "TV"),
    TW(itemName = "Taiwan, Province of China", value = "TW"),
    TZ(itemName = "Tanzania, United Republic of", value = "TZ"),
    UG(itemName = "Uganda", value = "UG"),
    UA(itemName = "Ukraine", value = "UA"),
    UM(itemName = "United States Minor Outlying Islands", value = "UM"),
    UY(itemName = "Uruguay", value = "UY"),
    US(itemName = "United States", value = "US"),
    UZ(itemName = "Uzbekistan", value = "UZ"),
    VA(itemName = "Holy See (Vatican City State)", value = "VA"),
    VC(itemName = "Saint Vincent and the Grenadines", value = "VC"),
    VE(itemName = "Venezuela, Bolivarian Republic of", value = "VE"),
    VG(itemName = "Virgin Islands, British", value = "VG"),
    VI(itemName = "Virgin Islands, U.S.", value = "VI"),
    VN(itemName = "Viet Nam", value = "VN"),
    VU(itemName = "Vanuatu", value = "VU"),
    WF(itemName = "Wallis and Futuna", value = "WF"),
    WS(itemName = "Samoa", value = "WS"),
    YE(itemName = "Yemen", value = "YE"),
    ZA(itemName = "South Africa", value = "ZA"),
    ZM(itemName = "Zambia", value = "ZM"),
    ZW(itemName = "Zimbabwe", value = "ZW");

    companion object : SettingItem.SettingItemCompanion {
        override val DEFAULT = JP
        override fun valueOfOrDefault(name: String) = try {
            valueOf(name)
        } catch (e: IllegalArgumentException) {
            DEFAULT
        }
    }
}